### ISSUE TITLE
GetMappedResult returns null for IEnumerable<IContentItemFieldsSource>

### ISSUE THREAD

**Issue by bluemodus-sandro** [Kentico/xperience-by-kentico-kentico-migration-tool#354]
### Brief bug description

For all migrated items, GetMappedResult returns null for IEnumerable<IContentItemFieldsSource> fields on the migrated types.

These are typically "Legacy Media" items. The media item is visible in the selector when editing the migrated page in the content tree. It is also possible to click "Edit" on the media item, and it correctly goes to the Edit screen in the Content Hub, where the image is also visible.

To work around the issue, I need to deselect the content item on the Page in the tree and then re-select the same content item. Once I do that, GetMappedResult correctly returns the content item in the property of that page. Additionally, if there are 3 different properties of type IEnumerable<IContentItemFieldsSource> that are initially null, deselecting then reselecting just one will "fix" all three properties. 

## Output logs

There are no errors related to the page and content items in question. 

### Repro steps

1. Go to a migrated page in the content tree and note that media items are visible
2. Query the page with the ContentQueryExecutor.GetMappedResult and note that the media fields \ properties are null
3. Go to the migrated page in the tree, deselect the media item, then reselect it
4. Query the page with the ContentQueryExecutor.GetMappedResult and note that the media fields \ properties are populated

### Test environment

v30.1.1

**Comment by akfakmot** [comment]
Hi @twozero6,

is the database, that your query operates on, a result of migration by the newest MT release (2.4.0) or some previous version. If it was migrated by older version, is it possible to remigrate using 2.4.0? We've fixed a similar issue in 2.4.0. 

If remigration is not possible, I would ask you for .bak backup of your disfunctional database. I'd be able to identify if the fixed bug is the root cause and provide a patch script.

Thanks

**Comment by twozero6** [comment]
Hi @akfakmot, I just upgraded to 2.4.0 and confirmed I am seeing the same issue. Let me know if a copy of my DB would be helpful. Thank you!

**Comment by akfakmot** [comment]
@twozero6 Thanks. Yes, a copy of the source database is a guaranteed way to find out what's wrong

**Comment by twozero6** [comment]
@akfakmot I uploaded it to the same shared drive as before. It's the one ending in ***-com-2020 - I uploaded both a bacpac and a bak file. Thank you!

**Comment by akfakmot** [comment]
https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/pull/100

**Comment by akfakmot** [comment]
@bluemodus-sandro

This is fixed in new release https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/releases/tag/v3.1.0
Can I ask you to confirm the problem is solved?

Thank you

**Comment by bluemodus-sandro** [comment]
@akfakmot I upgraded to 3.1.0 but unfortunately I'm still seeing the same issue. References like these are null until I edit the page, deselect either of these items and then reselect it. After that, they populate the property as expected.

```
public IEnumerable<HeroItem> HeroItem { get; set; }
public IEnumerable<IContentItemFieldsSource> PageImage { get; set; }
```

**Comment by akfakmot** [comment]
Hello @bluemodus-sandro 

My tests pass OK. I use this simple code to check

```
app.MapGet("/", async (IContentQueryExecutor exe) =>
{
    var items = await exe.GetMappedWebPageResult<ContentBase.Page>(new ContentItemQueryBuilder().ForContentType(ContentBase.Page.CONTENT_TYPE_NAME, x => x.WithLinkedItems(1)));
});
```

And these is a peek at returned values at runtime. The linked image is there.
![Image](https://github.com/user-attachments/assets/576d4dc1-6039-4971-b255-bb401559c0f2)

The symptoms you describe could be caused by missing WithLinkedItems call.

For further investigation I would need more concrete steps - e.g. GUID of some nonfunctioning page in the target instance.

**Comment by akfakmot** [comment]
I assume you're filling HeroFields.HeroItem with ContentBase_HomePage.Related_Hero. Can you share the code that does this? Or even better share the full custom mapping code.

However I see one problem - Related_Hero field selector is set to allow ContentBase.Hero page types. But the table ContentBase_Hero in the backup you've shared doesn't contain any rows.

**Comment by bluemodus-sandro** [comment]
@akfakmot I am uploading the migration project now - it will be available in 10 minutes or so in that same shared drive. However, the ClassName is ContentBase_Hero but the table that the class uses is ClientNamespace_Hero and there should be one record in there.

**Comment by akfakmot** [comment]
@bluemodus-sandro I see. I'll be on it as soon as it uploads.

**Comment by akfakmot** [comment]
@bluemodus-sandro I found the problem. I'll provide you with a temporary solution. On Monday we'll emit a release.

**Comment by bluemodus-sandro** [comment]
@akfakmot the temporary fix did help with this issue but with it, a lot of the items that are referencing other content items have this in the database:

![Image](https://github.com/user-attachments/assets/e9fc85be-e77b-435b-bdb1-5375d22e51c4)

That field is on a reusable schema so I am not doing any additional conversions with the field values - it was correctly being set to NULL or a content item identifier before this change. I think those values are causing the Content tab to fail in the tree with this error:

```
Message: Cannot find a web page item with the ContentItemID 359.

Exception type: System.InvalidOperationException
Stack trace: 
   at Kentico.Xperience.Admin.Websites.WebPageItemNavigationProvider.GetSlugs(Int32 contentItemID, String languageName, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Websites.WebPageItemNavigationProvider.GetEditNavigation(Int32 contentItemID, String languageName, PreferredTab preferredTab, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Base.UIPages.ContentItemNavigationPathRetriever.GetEditNavigationPath(Int32 contentItemId, Int32 languageId, Int32 workspaceId, Int32 channelId, PreferredTab preferredTab, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProvider.GetItemNavigateToPath(Int32 workspaceId, Int32 languageId, Int32 contentItemId, Int32 channelId, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProviderBase.GetItem(IDataContainer dataContainer, Int32 sourceLanguageId, IReadOnlyCollection`1 liveSiteFallbackChain, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProviderBase.Get(IEnumerable`1 references, Int32 contentLanguageId, CancellationToken cancellationToken)
   at Kentico.Xperience.Admin.Base.Forms.ContentItemSelectorComponentBase`1.SetItems(ContentItemSelectorClientProperties clientProperties)
   at Kentico.Xperience.Admin.Base.Forms.ContentItemSelectorComponentBase`1.ConfigureClientProperties(ContentItemSelectorClientProperties clientProperties)
   at Kentico.Xperience.Admin.Base.Forms.ContentItemSelectorComponent.ConfigureClientProperties(ContentItemSelectorClientProperties clientProperties)
   at Kentico.Xperience.Admin.Base.Forms.FormComponent`3.GetClientProperties()
   at Kentico.Xperience.Admin.Base.Forms.FormComponent`3.Kentico.Xperience.Admin.Base.Forms.IFormItem.GetClientProperties()
   at Kentico.Xperience.Admin.Base.Forms.FormItemExtensions.<>c.<<GetClientProperties>b__4_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Kentico.Xperience.Admin.Base.Forms.IEnumerableExtensions.AwaitEachElement[TSource,TResult](IEnumerable`1 source, Func`2 predicate)
   at Kentico.Xperience.Admin.Base.Forms.FormItemExtensions.GetClientProperties(IEnumerable`1 formItems)
   at Kentico.Xperience.Admin.Websites.UIPages.ContentTab.GetFormItems(WebPageAdminModel page)
   at Kentico.Xperience.Admin.Websites.UIPages.ContentTab.ConfigureTemplateProperties(ContentTabClientProperties properties)
   at Kentico.Xperience.Admin.Base.Page`1.Kentico.Xperience.Admin.Base.IPage.GetConfiguredTemplateProperties()
   at Kentico.Xperience.Admin.Base.PageInvoker.InvokePage(String path)
   at Kentico.Xperience.Admin.Base.KenticoAdministrationController.GetPageConfiguration(PageConfigurationRequestModel pageConfigurationRequest)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Kentico.Xperience.Admin.Base.AntiforgeryMiddleware.InvokeAsync(HttpContext context)
   at Kentico.Web.Mvc.Internal.DefaultAdminSchemeAuthenticationMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Kentico.Xperience.Admin.Base.AdminLocalizationMiddleware.InvokeAsync(HttpContext context)
   at Kentico.Web.Mvc.KenticoRequestEventsMiddleware.InvokeAsync(HttpContext context)
   at Kentico.Web.Mvc.KenticoErrorHandlingMiddleware.InvokeAsync(HttpContext context, ILogger`1 logger)

```

**Comment by akfakmot** [comment]
Hi @bluemodus-sandro 

Thanks for pointing this out. Fix is prepared and will be released tomorrow asap.

**Comment by akfakmot** [comment]
@bluemodus-sandro 

Release 3.1.1 contains the fix https://github.com/Kentico/xperience-by-kentico-kentico-migration-tool/releases/tag/v3.1.1

Please let me know if it helped

**Comment by akfakmot** [comment]
@bluemodus-sandro Glad to hear it. Thanks for all your feedbacks
